spring.application.name=bank_system_sample
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_system_db
spring.datasource.username=Your_Username
spring.datasource.password=Your_Password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
